export const MusicSymbol = {
    augmentationDot: '\u{E1E7}',
    caesuraThick: '\u{E4D2}',
    cClef: '\u{E05C}',
    coda: '\u{E048}',
    codaSquare: '\u{E049}',
    daCapo: '\u{E046}',
    dynamicFF: '\u{E52F}',
    dynamicFFF: '\u{E530}',
    dynamicFFFF: '\u{E531}',
    dynamicFFFFF: '\u{E532}',
    dynamicFFFFFF: '\u{E533}',
    dynamicForte: '\u{E522}',
    dynamicFortePiano: '\u{E534}',
    dynamicForteSmall: '\u{F46D}',
    dynamicForzando: '\u{E535}',
    dynamicMessaDiVoce: '\u{E540}',
    dynamicMezzo: '\u{E521}',
    dynamicMezzoSmall: '\u{F46C}',
    dynamicMF: '\u{E52D}',
    dynamicMP: '\u{E52C}',
    dynamicPF: '\u{E52E}',
    dynamicPiano: '\u{E520}',
    dynamicPianoSmall: '\u{F46B}',
    dynamicPP: '\u{E52B}',
    dynamicPPP: '\u{E52A}',
    dynamicPPPP: '\u{E529}',
    dynamicPPPPP: '\u{E528}',
    dynamicPPPPPP: '\u{E527}',
    fClef: '\u{E062}',
    fermataAbove: '\u{E4C0}',
    fermataBelow: '\u{E4C1}',
    fermataLongAbove: '\u{E4C6}',
    fermataLongBelow: '\u{E4C7}',
    fermataLongHenzeAbove: '\u{E4CA}',
    fermataLongHenzeBelow: '\u{E4CB}',
    gClef: '\u{E050}',
    metNoteWhole: '\u{ECA2}',
    note8thUp: '\u{E1D7}',
    noteHalfUp: '\u{E1D3}',
    noteQuarterUp: '\u{E1D5}',
    repeat1Bar: '\u{E500}',
    repeatLeft: '\u{E040}',
    repeatRight: '\u{E041}',
    rest8th: '\u{E4E6}',
    restHalfLegerLine: '\u{E4F5}',
    restQuarter: '\u{E4E5}',
    restWholeLegerLine: '\u{E4F4}',
    timeSig12over8: '\u{F605}',
    timeSig0: '\u{E080}',
    timeSig0Denominator: '\u{F5C8}',
    timeSig0Numerator: '\u{F5C9}',
    timeSig1: '\u{E081}',
    timeSig1Denominator: '\u{F5CA}',
    timeSig1Numerator: '\u{F5CB}',
    timeSig2: '\u{E082}',
    timeSig2Denominator: '\u{F5CC}',
    timeSig2Numerator: '\u{F5CD}',
    timeSig2over2: '\u{F5FA}',
    timeSig2over4: '\u{F5F9}',
    timeSig3: '\u{E083}',
    timeSig3Denominator: '\u{F5CE}',
    timeSig3Numerator: '\u{F5CF}',
    timeSig3over2: '\u{F5FB}',
    timeSig3over4: '\u{F5FC}',
    timeSig3over8: '\u{F5FD}',
    timeSig4: '\u{E084}',
    timeSig4Denominator: '\u{F5D0}',
    timeSig4Numerator: '\u{F5D1}',
    timeSig4over4: '\u{F5FE}',
    timeSig5: '\u{E085}',
    timeSig5Denominator: '\u{F5D2}',
    timeSig5Numerator: '\u{F5D3}',
    timeSig5over4: '\u{F5FF}',
    timeSig5over8: '\u{F600}',
    timeSig6: '\u{E086}',
    timeSig6Denominator: '\u{F5D4}',
    timeSig6Numerator: '\u{F5D5}',
    timeSig6over4: '\u{F601}',
    timeSig6over8: '\u{F602}',
    timeSig7: '\u{E087}',
    timeSig7Denominator: '\u{F5D6}',
    timeSig7Numerator: '\u{F5D7}',
    timeSig7over8: '\u{F603}',
    timeSig8: '\u{E088}',
    timeSig8Denominator: '\u{F5D8}',
    timeSig8Numerator: '\u{F5D9}',
    timeSig9: '\u{E089}',
    timeSig9Denominator: '\u{F5DA}',
    timeSig9Numerator: '\u{F5DB}',
    timeSig9over8: '\u{F604}',
} as const;

export type MusicSymbolItem = {
    name: MusicSymbolName;
    value: string;
    codePoint: string;
    category: string;
};
export type MusicSymbolName = keyof typeof MusicSymbol;
export type MusicSymbolValue = (typeof MusicSymbol)[MusicSymbolName];

export type MusicSymbolOption = {
    label: string;
    value: MusicSymbolValue;
};

export type MusicSymbolCategory = {
    label: string;
    symbols: MusicSymbolOption[];
};

export const MusicSymbolCategories: MusicSymbolCategory[] = [
    {
        label: 'Notes',
        symbols: [
            { label: "Point d'augmentation", value: MusicSymbol.augmentationDot },
            { label: 'Ronde', value: MusicSymbol.metNoteWhole },
            { label: 'Blanche', value: MusicSymbol.noteHalfUp },
            { label: 'Noire', value: MusicSymbol.noteQuarterUp },
            { label: 'Croche', value: MusicSymbol.note8thUp },
        ],
    },
    {
        label: 'Silences',
        symbols: [
            { label: 'Pause', value: MusicSymbol.restWholeLegerLine },
            { label: 'Demi-pause', value: MusicSymbol.restHalfLegerLine },
            { label: 'Soupir', value: MusicSymbol.restQuarter },
            { label: 'Demi-soupir', value: MusicSymbol.rest8th },
        ],
    },
    {
        label: 'Clés',
        symbols: [
            { label: 'Clé de sol', value: MusicSymbol.gClef },
            { label: 'Clé de fa', value: MusicSymbol.fClef },
            { label: "Clé d'ut", value: MusicSymbol.cClef },
        ],
    },
    {
        label: 'Nuances',
        symbols: [
            { label: 'Pianissimo × 6', value: MusicSymbol.dynamicPPPPPP },
            { label: 'Pianissimo × 5', value: MusicSymbol.dynamicPPPPP },
            { label: 'Pianissimo × 4', value: MusicSymbol.dynamicPPPP },
            { label: 'Pianissimo × 3', value: MusicSymbol.dynamicPPP },
            { label: 'Pianissimo', value: MusicSymbol.dynamicPP },
            { label: 'Piano', value: MusicSymbol.dynamicPiano },
            { label: 'Piano petit', value: MusicSymbol.dynamicPianoSmall },
            { label: 'Mezzo-piano', value: MusicSymbol.dynamicMP },
            { label: 'Mezzo', value: MusicSymbol.dynamicMezzo },
            { label: 'Mezzo petit', value: MusicSymbol.dynamicMezzoSmall },
            { label: 'Mezzo-forte', value: MusicSymbol.dynamicMF },
            { label: 'Forte', value: MusicSymbol.dynamicForte },
            { label: 'Forte petit', value: MusicSymbol.dynamicForteSmall },
            { label: 'Fortissimo', value: MusicSymbol.dynamicFF },
            { label: 'Fortissimo × 3', value: MusicSymbol.dynamicFFF },
            { label: 'Fortissimo × 4', value: MusicSymbol.dynamicFFFF },
            { label: 'Fortissimo × 5', value: MusicSymbol.dynamicFFFFF },
            { label: 'Fortissimo × 6', value: MusicSymbol.dynamicFFFFFF },
            { label: 'Piano-forte', value: MusicSymbol.dynamicPF },
            { label: 'Forte-piano', value: MusicSymbol.dynamicFortePiano },
            { label: 'Forzando', value: MusicSymbol.dynamicForzando },
            { label: 'Messa di voce', value: MusicSymbol.dynamicMessaDiVoce },
        ],
    },
    {
        label: 'Indications de mesure',
        symbols: [
            { label: 'Chiffre 0', value: MusicSymbol.timeSig0 },
            { label: 'Chiffre 1', value: MusicSymbol.timeSig1 },
            { label: 'Chiffre 2', value: MusicSymbol.timeSig2 },
            { label: 'Chiffre 3', value: MusicSymbol.timeSig3 },
            { label: 'Chiffre 4', value: MusicSymbol.timeSig4 },
            { label: 'Chiffre 5', value: MusicSymbol.timeSig5 },
            { label: 'Chiffre 6', value: MusicSymbol.timeSig6 },
            { label: 'Chiffre 7', value: MusicSymbol.timeSig7 },
            { label: 'Chiffre 8', value: MusicSymbol.timeSig8 },
            { label: 'Chiffre 9', value: MusicSymbol.timeSig9 },
            { label: 'Numérateur 0', value: MusicSymbol.timeSig0Numerator },
            { label: 'Numérateur 1', value: MusicSymbol.timeSig1Numerator },
            { label: 'Numérateur 2', value: MusicSymbol.timeSig2Numerator },
            { label: 'Numérateur 3', value: MusicSymbol.timeSig3Numerator },
            { label: 'Numérateur 4', value: MusicSymbol.timeSig4Numerator },
            { label: 'Numérateur 5', value: MusicSymbol.timeSig5Numerator },
            { label: 'Numérateur 6', value: MusicSymbol.timeSig6Numerator },
            { label: 'Numérateur 7', value: MusicSymbol.timeSig7Numerator },
            { label: 'Numérateur 8', value: MusicSymbol.timeSig8Numerator },
            { label: 'Numérateur 9', value: MusicSymbol.timeSig9Numerator },
            { label: 'Dénominateur 0', value: MusicSymbol.timeSig0Denominator },
            { label: 'Dénominateur 1', value: MusicSymbol.timeSig1Denominator },
            { label: 'Dénominateur 2', value: MusicSymbol.timeSig2Denominator },
            { label: 'Dénominateur 3', value: MusicSymbol.timeSig3Denominator },
            { label: 'Dénominateur 4', value: MusicSymbol.timeSig4Denominator },
            { label: 'Dénominateur 5', value: MusicSymbol.timeSig5Denominator },
            { label: 'Dénominateur 6', value: MusicSymbol.timeSig6Denominator },
            { label: 'Dénominateur 7', value: MusicSymbol.timeSig7Denominator },
            { label: 'Dénominateur 8', value: MusicSymbol.timeSig8Denominator },
            { label: 'Dénominateur 9', value: MusicSymbol.timeSig9Denominator },
            { label: 'Mesure 2/2', value: MusicSymbol.timeSig2over2 },
            { label: 'Mesure 2/4', value: MusicSymbol.timeSig2over4 },
            { label: 'Mesure 3/2', value: MusicSymbol.timeSig3over2 },
            { label: 'Mesure 3/4', value: MusicSymbol.timeSig3over4 },
            { label: 'Mesure 3/8', value: MusicSymbol.timeSig3over8 },
            { label: 'Mesure 4/4', value: MusicSymbol.timeSig4over4 },
            { label: 'Mesure 5/4', value: MusicSymbol.timeSig5over4 },
            { label: 'Mesure 5/8', value: MusicSymbol.timeSig5over8 },
            { label: 'Mesure 6/4', value: MusicSymbol.timeSig6over4 },
            { label: 'Mesure 6/8', value: MusicSymbol.timeSig6over8 },
            { label: 'Mesure 7/8', value: MusicSymbol.timeSig7over8 },
            { label: 'Mesure 9/8', value: MusicSymbol.timeSig9over8 },
            { label: 'Mesure 12/8', value: MusicSymbol.timeSig12over8 },
        ],
    },
    {
        label: 'Reprises et navigation',
        symbols: [
            { label: 'Barre de reprise gauche', value: MusicSymbol.repeatLeft },
            { label: 'Barre de reprise droite', value: MusicSymbol.repeatRight },
            { label: "Répétition d'une mesure", value: MusicSymbol.repeat1Bar },
            { label: 'Coda', value: MusicSymbol.coda },
            { label: 'Coda carrée', value: MusicSymbol.codaSquare },
            { label: 'Da capo', value: MusicSymbol.daCapo },
        ],
    },
    {
        label: "Points d'orgue et respirations",
        symbols: [
            { label: 'Césure épaisse', value: MusicSymbol.caesuraThick },
            { label: "Point d'orgue supérieur", value: MusicSymbol.fermataAbove },
            { label: "Point d'orgue inférieur", value: MusicSymbol.fermataBelow },
            { label: "Point d'orgue long supérieur", value: MusicSymbol.fermataLongAbove },
            { label: "Point d'orgue long inférieur", value: MusicSymbol.fermataLongBelow },
            { label: "Point d'orgue long Henze supérieur", value: MusicSymbol.fermataLongHenzeAbove },
            { label: "Point d'orgue long Henze inférieur", value: MusicSymbol.fermataLongHenzeBelow },
        ],
    },
];

export const getMusicSymbol = (name: MusicSymbolName): MusicSymbolValue => MusicSymbol[name];
const getSymbolCategory = (name: string): string => {
    const match = name.match(/^[a-z]+/i);
    return match?.[0] ?? 'other';
};

export const MusicSymbolList: MusicSymbolItem[] = Object.entries(MusicSymbol).map(([name, value]) => ({
    name: name as MusicSymbolName,
    value,
    codePoint: `U+${value.codePointAt(0)?.toString(16).toUpperCase()}`,
    category: getSymbolCategory(name),
}));
