export const MusicSymbol = {
    augmentationDot: '\u{E1E7}',
    caesuraThick: '\u{E4D2}',
    cClef: '\u{E05C}',
    coda: '\u{E048}',
    codaSquare: '\u{E049}',
    daCapo: '\u{E046}',
    dynamicFF: '\u{E52F}',
    dynamicFFF: '\u{E530}',
    dynamicFFFF: '\u{E531}',
    dynamicFFFFF: '\u{E532}',
    dynamicFFFFFF: '\u{E533}',
    dynamicForte: '\u{E522}',
    dynamicFortePiano: '\u{E534}',
    dynamicForteSmall: '\u{F46D}',
    dynamicForzando: '\u{E535}',
    dynamicMessaDiVoce: '\u{E540}',
    dynamicMezzo: '\u{E521}',
    dynamicMezzoSmall: '\u{F46C}',
    dynamicMF: '\u{E52D}',
    dynamicMP: '\u{E52C}',
    dynamicPF: '\u{E52E}',
    dynamicPiano: '\u{E520}',
    dynamicPianoSmall: '\u{F46B}',
    dynamicPP: '\u{E52B}',
    dynamicPPP: '\u{E52A}',
    dynamicPPPP: '\u{E529}',
    dynamicPPPPP: '\u{E528}',
    dynamicPPPPPP: '\u{E527}',
    fClef: '\u{E062}',
    fermataAbove: '\u{E4C0}',
    fermataBelow: '\u{E4C1}',
    fermataLongAbove: '\u{E4C6}',
    fermataLongBelow: '\u{E4C7}',
    fermataLongHenzeAbove: '\u{E4CA}',
    fermataLongHenzeBelow: '\u{E4CB}',
    gClef: '\u{E050}',
    metNoteWhole: '\u{ECA2}',
    note8thUp: '\u{E1D7}',
    noteHalfUp: '\u{E1D3}',
    noteQuarterUp: '\u{E1D5}',
    repeat1Bar: '\u{E500}',
    repeatLeft: '\u{E040}',
    repeatRight: '\u{E041}',
    rest8th: '\u{E4E6}',
    restHalfLegerLine: '\u{E4F5}',
    restQuarter: '\u{E4E5}',
    restWholeLegerLine: '\u{E4F4}',
    timeSig12over8: '\u{F605}',
    timeSig0: '\u{E080}',
    timeSig0Denominator: '\u{F5C8}',
    timeSig0Numerator: '\u{F5C9}',
    timeSig1: '\u{E081}',
    timeSig1Denominator: '\u{F5CA}',
    timeSig1Numerator: '\u{F5CB}',
    timeSig2: '\u{E082}',
    timeSig2Denominator: '\u{F5CC}',
    timeSig2Numerator: '\u{F5CD}',
    timeSig2over2: '\u{F5FA}',
    timeSig2over4: '\u{F5F9}',
    timeSig3: '\u{E083}',
    timeSig3Denominator: '\u{F5CE}',
    timeSig3Numerator: '\u{F5CF}',
    timeSig3over2: '\u{F5FB}',
    timeSig3over4: '\u{F5FC}',
    timeSig3over8: '\u{F5FD}',
    timeSig4: '\u{E084}',
    timeSig4Denominator: '\u{F5D0}',
    timeSig4Numerator: '\u{F5D1}',
    timeSig4over4: '\u{F5FE}',
    timeSig5: '\u{E085}',
    timeSig5Denominator: '\u{F5D2}',
    timeSig5Numerator: '\u{F5D3}',
    timeSig5over4: '\u{F5FF}',
    timeSig5over8: '\u{F600}',
    timeSig6: '\u{E086}',
    timeSig6Denominator: '\u{F5D4}',
    timeSig6Numerator: '\u{F5D5}',
    timeSig6over4: '\u{F601}',
    timeSig6over8: '\u{F602}',
    timeSig7: '\u{E087}',
    timeSig7Denominator: '\u{F5D6}',
    timeSig7Numerator: '\u{F5D7}',
    timeSig7over8: '\u{F603}',
    timeSig8: '\u{E088}',
    timeSig8Denominator: '\u{F5D8}',
    timeSig8Numerator: '\u{F5D9}',
    timeSig9: '\u{E089}',
    timeSig9Denominator: '\u{F5DA}',
    timeSig9Numerator: '\u{F5DB}',
    timeSig9over8: '\u{F604}',
} as const;

export type MusicSymbolItem = {
    name: MusicSymbolName;
    value: string;
    codePoint: string;
    category: string;
};
export type MusicSymbolName = keyof typeof MusicSymbol;
export type MusicSymbolValue = (typeof MusicSymbol)[MusicSymbolName];

export const getMusicSymbol = (name: MusicSymbolName): MusicSymbolValue => MusicSymbol[name];
const getSymbolCategory = (name: string): string => {
    const match = name.match(/^[a-z]+/i);
    return match?.[0] ?? 'other';
};

export const MusicSymbolList: MusicSymbolItem[] = Object.entries(MusicSymbol).map(([name, value]) => ({
    name: name as MusicSymbolName,
    value,
    codePoint: `U+${value.codePointAt(0)?.toString(16).toUpperCase()}`,
    category: getSymbolCategory(name),
}));
